server:
  port: 9090
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/elementui?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: artolia
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  session:
    store-type: none
  security:
    user:
      name: user
      password: password
      roles: USER
logback:
  logdir: d:/log/element-admin
  appname: element-admin
security:
  jwt:
    token:
      secret-key: mysecret
      expire-length: 3600000
